const pictures = {
    bosque: [
        'bosque1.jpg',
        'bosque2.jpg',
        'bosque3.jpg',
        'bosque4.jpg',
        'bosque5.jpg',
        'bosque6.jpg',
        'bosque7.jpg',
        'bosque8.jpg',
        'bosque9.jpg',
        'bosque10.jpg',
        'bosque11.jpg',
        'bosque12.jpg',
        'bosque13.jpg',
        'bosque14.jpg',
        'bosque15.jpg',
        'bosque16.jpg',
        'bosque17.jpg'
    ],
    rio: [
        'rio1.jpg',
        'rio2.jpg',
        'rio3.jpg',
        'rio4.jpg',
        'rio5.jpg',
        'rio6.jpg',
        'rio7.jpg',
        'rio8.jpg',
    ],
    parque: [
        'parque1.jpg',
        'parque2.jpg',
        'parque3.jpg',
    ],
    casa: [
        'casa1.jpg',
        'casa2.jpg',
        'casa3.jpg',
        'casa4.jpg',
        'casa5.jpg',
        'casa6.jpg',
        'casa7.jpg',
        'casa8.jpg',
    ],
    otras: [
        'otras1.jpg',
        'otras2.jpg',
        'otras3.jpg',
        'otras4.jpg',
        'otras5.jpg',
        'otras6.jpg',
        'otras7.jpg',
        'otras8.jpg',
        'otras9.jpg',
        'otras10.jpg',
        'otras11.jpg',
        'otras12.jpg',
        'otras13.jpg',
        'otras14.jpg',
    ],
    privadas: [
        'privada1.jpg',
        'privada2.jpg',
        'privada3.jpg',
    ]
};

export default pictures;